spring:
  application:
    name: presentation
  datasource:
    url: jdbc:postgresql://localhost:5430/net_metrics
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
community:
  string: skorik
VK:
  VK_TOKEN: ${VK_TOKEN}
  GROUP_ID: ${GROUP_ID}